///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/

// To parse this JSON data, do
//
//     final login = loginFromJson(jsonString);

class LoginModel {
/*
{
  "access_token": "pZkUvpktdwxrdJ4FKj7UUN0M30ZDSFa4C6Y487FGRAz7SQHS7DNAuAuxuDeYIG4pNuiUgq0IsyUS4WekXTB-eQfvCjCIF-HQgqDIIn5EbfJOssJQhVJCd2Yj3_Lj6i22odtyTs68zyMJRbUeHXy2ysxYpV5YLpO_cq_QPenlzDrwr-NXJ4Ex3SrfQJTX1rKlhdWcrNgPxs8p8_50iUB79NY7zmsOrKelGaopjfVKtbaNroKNWfFu5ZrNvMT8VsVC",
  "token_type": "bearer",
  "expires_in": 86399
}
*/

  String? accessToken;
  String? tokenType;
  int? expiresIn;

  LoginModel({
    this.accessToken,
    this.tokenType,
    this.expiresIn,
  });

  LoginModel.fromJson(Map<String, dynamic> json) {
    accessToken = json['access_token']?.toString();
    tokenType = json['token_type']?.toString();
    expiresIn = json['expires_in']?.toInt();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['access_token'] = accessToken;
    data['token_type'] = tokenType;
    data['expires_in'] = expiresIn;
    return data;
  }
}

/// QUİCKTYPE sitesindeki model

/*import 'dart:convert';

Login loginFromJson(String str) => Login.fromJson(json.decode(str));

String loginToJson(Login data) => json.encode(data.toJson());

class Login {
  Login({
    required this.accessToken,
    required this.tokenType,
    required this.expiresIn,
  });

  String accessToken;
  String tokenType;
  int expiresIn;

  factory Login.fromJson(Map<String, dynamic> json) => Login(
        accessToken: json["access_token"] == null ? null : json["access_token"],
        tokenType: json["token_type"] == null ? null : json["token_type"],
        expiresIn: json["expires_in"] == null ? null : json["expires_in"],
      );

  Map<String, dynamic> toJson() => {
        "access_token": accessToken == null ? null : accessToken,
        "token_type": tokenType == null ? null : tokenType,
        "expires_in": expiresIn == null ? null : expiresIn,
      };
}*/
